INSERT INTO RESTAURANTE (ID, NOME) VALUES (1, 'Restaurante da Dona Florinda');

INSERT INTO CARDAPIO (ID, RESTAURANTE_ID) VALUES (1, 1);

INSERT INTO SEGMENTO (ID, TIPO) VALUES (1, 'ENTRADA');
INSERT INTO SEGMENTO (ID, TIPO) VALUES (2, 'BEBIDA');
INSERT INTO SEGMENTO (ID, TIPO) VALUES (3, 'SOBREMESA');

INSERT INTO CARDAPIO_SEGMENTOS (CARDAPIO_ID, SEGMENTOS_ID) VALUES (1, 1);
INSERT INTO CARDAPIO_SEGMENTOS (CARDAPIO_ID, SEGMENTOS_ID) VALUES (1, 2);
INSERT INTO CARDAPIO_SEGMENTOS (CARDAPIO_ID, SEGMENTOS_ID) VALUES (1, 3);

INSERT INTO ITEM (ID, NOME, VALOR) VALUES (1, 'Salada temperada', 9.99);
INSERT INTO ITEM (ID, NOME, VALOR) VALUES (2, 'Suco de laranja', 6.99);
INSERT INTO ITEM (ID, NOME, VALOR) VALUES (3, 'Pudim', 5.99);

INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (1, 1);  
INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (2, 2);
INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (3, 3);