INSERT INTO RESTAURANTE (ID, NOME) VALUES (1, 'Restaurante da Dona Florinda');

INSERT INTO CARDAPIO (ID, RESTAURANTE_ID) VALUES (1, 1);

INSERT INTO SEGMENTO (ID, CARDAPIO_ID,  NOME) VALUES (1, 1, 'Entradas');
INSERT INTO SEGMENTO (ID, CARDAPIO_ID,  NOME) VALUES (2, 1, 'Bebidas');
INSERT INTO SEGMENTO (ID, CARDAPIO_ID,  NOME) VALUES (3, 1, 'Sobremesas');

INSERT INTO ITEM (ID, NOME, VALOR) VALUES (1, 'Salada temperada', 9.99);
INSERT INTO ITEM (ID, NOME, VALOR) VALUES (2, 'Suco de laranja', 6.99);
INSERT INTO ITEM (ID, NOME, VALOR) VALUES (3, 'Pudim', 5.99);

INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (1, 1);  
INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (2, 2);
INSERT INTO SEGMENTO_ITENS (ITENS_ID, SEGMENTO_ID) VALUES (3, 3);